### ISSUE TITLE
nice project! i want to help!

### ISSUE THREAD

**Issue by SilkePilon** [whatotter/pwnhyve#10]
i want to help with the front end!

**Comment by SilkePilon** [comment]
got an iso file for the build

**Comment by whatotter** [comment]
thank you! i already have a friend who will help when the time comes (should be in a few days or so, after the next update) - you guys can hopefully work together n just make a simplistic frontend
we dont have a place to really chat rn, but i'll probably make something like a discord server
ill gladly let you know

**Comment by SilkePilon** [comment]
👍

**Comment by EpicTia93** [comment]
> SilkePilon

Hey man let me know too if you make a discord server! Maybe I can do smth to help too.

**Comment by prometheus1987** [comment]
Ahoy. I'm looking for some open source projects to contribute to and I would love to help as well. I've been building Angular UIs since version 1. If there's anything I can do to help or collaborate with SilkePilon, please let me know! Cheers 🍻

**Comment by whatotter** [comment]
converted to discussion just in case other people want to join
