### ISSUE TITLE
Is there any setup guide available ?

### ISSUE THREAD

**Issue by jakre1234** [whatotter/pwnhyve#19]
Hi Devs, 
not an issue but wondering if there's a setup guide available for pwnhyve and does it support raspberry pi zero 2 w ?

Thanks and Regards,

**Comment by servebeer** [comment]
> Hi Devs, not an issue but wondering if there's a setup guide available for pwnhyve and does it support raspberry pi zero 2 w ?
> 
> Thanks and Regards,

@jakre1234 If you click on the "wiki" link above, is has a good setup and configuration guide.

**Comment by whatotter** [comment]
thank you 👍
