### ISSUE TITLE
Modules not working

### ISSUE THREAD

**Issue by Laughable33** [whatotter/pwnhyve#27]
Hey!

I am having an issue where when I go to use a module, for example /Wifi/Pwngotchi, clicking it does nothing. No pop-ups no gui, no nothing.

**Comment by whatotter** [comment]
thank you for opening the issue

can you show the logs of the pi? i'll try to recreate it

**Comment by whatotter** [comment]
nevermind it should be fixed, pushing the fix in a minute or so

**Comment by whatotter** [comment]
closed due to lack of activity
