### ISSUE TITLE
Run from a headless pi

### ISSUE THREAD

**Issue by igeometrix** [whatotter/pwnhyve#30]
I don't see in the documentation how exactly I can run this from a headless pi. How do configure it and then how do I actually get to control or select any of the modules. I basically have it setup on my pi to auto run like the documentation shows but can I say, ssh into the pi and get to a menu of sorts or am I going about it the wrong way?

**Comment by whatotter** [comment]
running headless is possible, but in the `config.toml` [VNC must be enabled](https://github.com/whatotter/pwnhyve/blob/main/config.toml#L12-L14). once that's done, you need to clone the pwnhyve repo to your PC, and then go to the vnc folder, then do `python3 stream.py (ip address of your pwnhyve pi)`.

if you want to do wifi hacking while using vnc you need a second wifi adapter, because when pwnhyve puts wlan0 into monitor mode it'll kill your session and you won't be able to get it back

VNC is also still experimental, report any issues you have on it :)

**Comment by igeometrix** [comment]
OK thank you, I got it going but sometimes the interface has info available and sometimes its just blank after I connect the IP. Maybe I should reinstall on my pi since I see you've been updating quite a bit lately. Is there a good way to just update a current install on my pi?

**Comment by igeometrix** [comment]
Main issue is that even when it connects and I have some options on the interface.. I only see a few and say I go into /Hotplug.. it then fails on the raspi side and disconnects from the stream.py. Do you have any input on this or do you think the update as I said above could fix all this? Also curious where the hoaxshell rev shell setup is at within the menus?

**Comment by whatotter** [comment]
> OK thank you, I got it going but sometimes the interface has info available and sometimes its just blank after I connect the IP. Maybe I should reinstall on my pi since I see you've been updating quite a bit lately. Is there a good way to just update a current install on my pi? 

as for right now, the systeminfo util is kinda broken and other plugins are being prioritised

and as for updating, you'd have to ssh into the pi and git clone the new repository - an auto update is in the works but redundancy is something highly prioritised too, so even if the update fails for some reason it should still work

**Comment by whatotter** [comment]
> Main issue is that even when it connects and I have some options on the interface.. I only see a few and say I go into /Hotplug.. it then fails on the raspi side and disconnects from the stream.py. Do you have any input on this or do you think the update as I said above could fix all this? Also curious where the hoaxshell rev shell setup is at within the menus? 

as for the raspi issue, I've never seen that happen and i use the vnc plugin almost daily, try git cloning the new repository on your pi and then show the logs here 🙂

the hoax shell plugin is being reworked at the moment but it should be under /Hotplug afaik, if not then it should be implemented next update (if I'm not lazy)

**Comment by igeometrix** [comment]
Here's some screens with the errors im getting.. some from my machine and some from the pi (ssh)
![pwnhyve1](https://github.com/whatotter/pwnhyve/assets/144109512/cbfe7666-3ddd-4029-bd49-955ab66fab8b)
![pwnhyve3](https://github.com/whatotter/pwnhyve/assets/144109512/6b70d28d-5d1f-46d1-bff5-92d366c73bd1)
![pwnhyve2](https://github.com/whatotter/pwnhyve/assets/144109512/6c59c063-1bbb-43a0-b83a-eadd3bb0c66a)
![pwnhyve4](https://github.com/whatotter/pwnhyve/assets/144109512/b6598461-2911-4882-919e-2bb14e9c0700)

**Comment by whatotter** [comment]
try updating the pi and then making sure you went [successfully through the badusb setup](https://github.com/whatotter/pwnhyve/wiki/installing#usb-module-run-on-boot), it might be because /dev/hidg0 doesn't exist, weird

**Comment by whatotter** [comment]
is the cable your using data? did you reboot the pi after installing? if you can, try a different port too

another thing you can try is doing `sudo /bin/pwnhyveusb` (or wherever your usb init module is) while the pi is connected

**Comment by wvpul** [comment]
Hi, i have been getting an error everytime i try to do "python stream.py my pi ip" 
![image](https://github.com/whatotter/pwnhyve/assets/87943190/0f67ddaf-6f2c-4b80-a898-a9999bcb27bf)

**Comment by whatotter** [comment]
closed due to inactivity, was fixed in the discord server
