### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by someguy1412** [whatotter/pwnhyve#35]
any usage for this? this is unclear to me

**Comment by someguy1412** [comment]
it runs fine now but i see zero modules
![image](https://github.com/whatotter/pwnhyve/assets/70436981/8a1852ae-8c51-47a0-a5ba-b4ca98dafd54)

**Comment by chufo4** [comment]
this is my alt and it has modules but they dont work

**Comment by whatotter** [comment]
sorry, the vnc module is still in heavy development atm so it might be very buggy

the controls are (iirc) the arrow keys as the joystick, 1,2,3 as the right side keys, and the forward slash key as joystick down

you could also click on the buttons with your mouse on the ui as if your using the real display

I'll switch the module to websockets eventually, so there won't be anymore socket issues

**Comment by someguy1412** [comment]
oh thanks, yeah i cant buy any oleds because none are in my region, so i said maybe i could use python for the vnc and get the display but yeah its heavily buggy sadly
