### ISSUE TITLE
Nothing showing up

### ISSUE THREAD

**Issue by Yolominium** [whatotter/pwnhyve#39]
Should I be able to see a menu or something similar upon boot? Currently, nothing appears except the login prompt. When I type systemctl start pwnhyve.service, I am prompted to authenticate, but nothing happens afterward.

**Comment by whatotter** [comment]
well it's supposed to appear on your oled, it's not a command-line application

if you don't have an oled you can use the vnc tool (`vnc/stream.py`) to connect to the pi

**Comment by Yolominium** [comment]
Thanks for replying
