### ISSUE TITLE
Howdy

### ISSUE THREAD

**Issue by NoobReider** [whatotter/pwnhyve#8]
- from instagram: add support for waveshare lcd

**Comment by NoobReider** [comment]
And in instalation ,what Wiki Are you talking about

**Comment by whatotter** [comment]
for the wiki, its https://github.com/whatotter/pwnhyve/wiki
as for support for the display, you would need to have the pi zero and waveshare lcd flashed with kali and have pwnhyve on it

to flash kali and have pwnhyve, just follow the wiki
