### ISSUE TITLE
How do i setup the 1.3" OLED hat

### ISSUE THREAD

**Issue by NoobReider** [whatotter/pwnhyve#9]

**Comment by whatotter** [comment]
just plug it in to the top, if its the waveshare oled in the github readme.md
pwnhyve should automatically find it

**Comment by whatotter** [comment]
i don't have visualization as of right now, but just something like this:

![71561MdE+oL _AC_SL1500_](https://github.com/whatotter/pwnhyve/assets/42103041/50fd85fa-4df0-4293-ab93-e9452aba45b1)

except the pi4 is your pi zero and its the oled instead of the lcd
